language: go

go:
  - 1.7

sudo: false

env:
  - GO15VENDOREXPERIMENT=1

install:
  - curl -L -s https://github.com/Masterminds/glide/releases/download/0.12.2/glide-linux-amd64.tar.gz | tar zxC ./
  - ./linux-amd64/glide install
