language: go

go:
  - 1.6
  - 1.7

sudo: false

install:
  - curl -L -s https://github.com/Masterminds/glide/releases/download/v0.12.2/glide-v0.12.2-linux-amd64.tar.gz | tar zxC ./
  - ./linux-amd64/glide install

script:
  - go test
